### ISSUE TITLE
Explore functionality?

### ISSUE THREAD

**Issue by sergiobdrl** [brownvc/neural-fields-review#11]
Your paper and webpage are a much-needed contribution to the Neural Rendering field.

I would like to suggest a functionality that I miss very much in your page: an exploration functionality.
When one first browses the webpage there are no papers on display, and the search box user-experience assumes the user already knows what they are looking for. It would be great if the page had a view with the latest/most-cited, papers, or an initial network view, etc.

**Comment by yxie20** [comment]
Thank you for your feedback. In the case that you are unfamiliar with the topic, our review paper is a good place for you to get started. You may also play with the "feeling lucky" button.

We have experimented with citation count with Google Scholar, but Google isn't friendly with bots. If you have a suggestion, please let us know!
